added AgentHistory model and its Repo.
racker/salus-telemetry-model pull request #154
Opened 2020-09-23 06:47 UTC by shabd67

# Resolves

[SALUS-796](https://jira.rax.io/browse/SALUS-796)

# What

Added AgentHistory Model and its Repo

2020-09-23 16:20 UTC, itzg requested changes
Any entity changes need flyway migrations added in https://github.com/racker/salus-telemetry-model/tree/master/src/main/resources/db/migration/mysql . I especially wanted to confirm indexes to ensure efficient execution of the repository query.

For research/spike issues we usually write up a proposal in https://github.com/Rackspace-Segment-Support/salus-docs-internal/tree/master/proposals and go through a PR review of that. Your approach looks straight forward, so a proposal probably wasn't needed in this case; however, what are your thoughts about:

- automatic/ongoing pruning of AgentHistory data
- APIs to retrieve agent history. At least a public API is needed

2020-09-23 16:20 UTC, itzg commented on src/main/java/com/rackspace/salus/telemetry/repositories/AgentHistoryRepository.java
> +      + "and a.connectedClosedAt IS NULL ORDER BY a.connectedAt DESC")
You actually didn't need to declare the JPQL here since the [inferred query method lookup](https://docs.spring.io/spring-data/jpa/docs/2.3.4.RELEASE/reference/html/#jpa.sample-app.finders.strategies) will handle these types of conditionals. [This appendix](https://docs.spring.io/spring-data/jpa/docs/2.3.4.RELEASE/reference/html/#repository-query-keywords) further expands upon the phrasing detected by that. I think an "IsNull" would be needed, `findAllByEnvoyIdAAndConnectedClosedAtIsNull`

2020-09-23 16:20 UTC, itzg commented on src/main/java/com/rackspace/salus/telemetry/entities/AgentHistory.java
> +  Instant connectedAt;
How about simply
```suggestion
  Instant connected;
```

2020-09-23 16:20 UTC, itzg commented on src/main/java/com/rackspace/salus/telemetry/entities/AgentHistory.java
> +  Instant connectedClosedAt;
...and
```suggestion
  Instant disconnected;
```

2020-09-23 16:20 UTC, itzg commented on src/main/java/com/rackspace/salus/telemetry/entities/AgentHistory.java
> +  String tenantID;
"ID" is always a weird one...we use strict camel case so these suffixes are always `Id`, such as [these](https://github.com/racker/salus-telemetry-model/blob/aa89a8eb4bb1f807e1becf783a8cf3115b22a87a/src/main/java/com/rackspace/salus/telemetry/entities/BoundMonitor.java#L118-L143)
```suggestion
  String tenantId;
```

2020-09-23 16:20 UTC, itzg commented on src/main/java/com/rackspace/salus/telemetry/entities/AgentHistory.java
> +  String resourceID;
```suggestion
  String resourceId;
```

2020-09-23 16:20 UTC, itzg commented on src/main/java/com/rackspace/salus/telemetry/entities/AgentHistory.java
> +  String envoyID;
```suggestion
  String envoyId;
```

2020-09-23 16:20 UTC, itzg commented on src/main/java/com/rackspace/salus/telemetry/entities/AgentHistory.java
> +  String remoteIP;
```suggestion
  String remoteIp;
```

2020-09-23 16:20 UTC, itzg commented on src/main/java/com/rackspace/salus/telemetry/entities/AgentHistory.java
> +  String zoneID;
```suggestion
  String zoneId;
```

2020-09-24 14:35 UTC, itzg requested changes

2020-09-24 14:35 UTC, itzg commented on src/main/resources/db/migration/common/V1_0__initial.sql
> +
You probably need to read up on Flyway. It's a big no-no to update an existing migration file:

https://flywaydb.org/documentation/migrations#versioned-migrations

Please put new schemas in a new file with an appropriate version identifier.

2020-09-24 14:35 UTC, itzg commented on src/main/resources/db/migration/common/V1_0__initial.sql
> +    on agent_history (envoy_id);
I think you'll need `tenant_id` added as first column of index. Then it'll support query for all envoy connections by tenant and also by specific envoy.

2020-09-24 14:37 UTC, shabd67 commented on src/main/resources/db/migration/common/V1_0__initial.sql
> +    on agent_history (envoy_id);
will take care of both.

2020-09-25 04:17 UTC, jjbuchan reviewed
Looks good once Geoff's suggestions are included.

While creating this did you notice if there's any other interesting fields we could log from the agent connection?  I'm not sure if there would be anything, just curious.

2020-09-25 04:17 UTC, jjbuchan commented on src/main/java/com/rackspace/salus/telemetry/entities/AgentHistory.java
> +  @Column(name ="connected_timestamp", nullable = false)
With all of these I wonder if we need a `@NotNull` as well?  @itzg do you remember if there were problems with not including it?

2020-09-25 09:15 UTC, shabd67 commented on src/main/resources/db/migration/common/V1_0__initial.sql
> +    on agent_history (envoy_id);
should I add resourceId also to the columns of index as @jjbuchan recommended to have a public api to get agent connection history with a resourceId?

2020-09-25 17:01 UTC, itzg commented on src/main/java/com/rackspace/salus/telemetry/entities/AgentHistory.java
> +  @Column(name ="connected_timestamp", nullable = false)
It's a bit tedious, but both are actually useful. The `@NotNull` will flag it earlier (and perhaps by IntelliJ). The `nullable = false` will declare the schema itself in MySQL to disallow null values...however, `nullable` is probably ignored since we manage schema via flyway.

2020-09-25 17:03 UTC, itzg commented on src/main/resources/db/migration/common/V1_0__initial.sql
> +    on agent_history (envoy_id);
Broadly, yes; however, it'll require two separate index declarations since the API request would drive queries by tenant+envoyId or tenant+resourceId.

2020-09-25 17:13 UTC, itzg commented on src/main/resources/db/migration/common/V9_2_add_agent_history.sql
> +    on agent_history (tenant_id, envoy_id);
Thinking more about [my comment on your proposal doc](https://github.com/Rackspace-Segment-Support/salus-docs-internal/pull/96#discussion_r494360334), I'm wondering if this should be a `create unique index` and your repository method can be simply:

```
Optional<AgentHistory> findByTenantIdAndEnvoyId(String tenantId, String envoyId);
```

2020-09-25 17:13 UTC, itzg commented on src/main/resources/db/migration/common/V9_2_add_agent_history.sql
> +create index byTenantOrEnvoyId
`byTenantOrEnvoyId` is a little misleading of a name. Compound indices require that if the 2nd, 3rd, etc columns are used in a query then all previous columns must be included. So the logical expression would be `by (tenant) or (tenant and envoy)`... but to keep it simple and use lower snakecase, I'd suggest:

```
by_tenant_envoy
```   

then the resourceId index would be named `by_tenant_resource_id`

2020-09-28 14:38 UTC, itzg commented on src/main/java/com/rackspace/salus/telemetry/repositories/AgentHistoryRepository.java
> +  List<AgentHistory> findAllByEnvoyIdAndDisconnectedAtIsNull(String envoyId);
[This comment](https://github.com/racker/salus-telemetry-model/pull/154#discussion_r495121684) seems to have gotten lost in the index changes.

2020-09-28 14:56 UTC, itzg reviewed
Looks like your flyway file disappeared in latest commit. BTW, it should be named with prefix `V10_0__` since it is not related to the `V9` files.

2020-09-28 15:04 UTC, shabd67 commented on src/main/java/com/rackspace/salus/telemetry/repositories/AgentHistoryRepository.java
> +  List<AgentHistory> findAllByEnvoyIdAndDisconnectedAtIsNull(String envoyId);
`findAllByEnvoyIdAndDisconnectedAtIsNull ` is being used to fetch latest connection for given envoyId and dump it into DB with connectionClosedAt time. 
```
List<AgentHistory> agents = agentHistoryRepository.findAllByEnvoyIdAndDisconnectedAtIsNull(envoyId);
    if(!agents.isEmpty()) {
      AgentHistory agentHistory = agents.get(0);
      final Instant connectionClosedTime = Instant.now();
      agentHistory.setDisconnectedAt(connectionClosedTime);
      agentHistoryRepository.save(agentHistory);
    }
```

2020-09-28 17:24 UTC, itzg commented on src/main/java/com/rackspace/salus/telemetry/repositories/AgentHistoryRepository.java
> +  Optional<AgentHistory> findByTenantIdAndResourceIdAndDisconnectedAtIsNull(String tenantId, String resourceId);
This one still needs to be pageable since it is used via the API and in that case would retrieve any number of envoy connections associated with that resourceId.

Also, why is the "AndDisconnectedAtIsNull" clause now showing up here?

2020-09-28 17:24 UTC, itzg commented on src/main/java/com/rackspace/salus/telemetry/repositories/AgentHistoryRepository.java
> +public interface AgentHistoryRepository extends CrudRepository<AgentHistory, UUID> {
It seems like you also need a query method to address https://github.com/Rackspace-Segment-Support/salus-docs-internal/pull/96#discussion_r494361434

2020-09-28 17:34 UTC, shabd67 commented on src/main/java/com/rackspace/salus/telemetry/repositories/AgentHistoryRepository.java
> +  Optional<AgentHistory> findByTenantIdAndResourceIdAndDisconnectedAtIsNull(String tenantId, String resourceId);
@itzg , I got your point for "findByTenantIdAndResourceId", but for findByTenantIdAndEnvoyId, will it be Pageable as well? actually I am using same method to update recently closed envoy connection with disconnectedAt column.

2020-09-28 17:35 UTC, shabd67 commented on src/main/java/com/rackspace/salus/telemetry/repositories/AgentHistoryRepository.java
> +public interface AgentHistoryRepository extends CrudRepository<AgentHistory, UUID> {
yes, I will be needing one for that.

2020-09-28 17:44 UTC, shabd67 commented on src/main/java/com/rackspace/salus/telemetry/repositories/AgentHistoryRepository.java
> +  Optional<AgentHistory> findByTenantIdAndResourceIdAndDisconnectedAtIsNull(String tenantId, String resourceId);
while at api side, findByTenantIdAndResourceId and findByTenantId will return a PagedContent while findByTenantIdAndEnvoyId will return an Optional.

2020-09-28 17:49 UTC, itzg commented on src/main/java/com/rackspace/salus/telemetry/repositories/AgentHistoryRepository.java
> +  Optional<AgentHistory> findByTenantIdAndResourceIdAndDisconnectedAtIsNull(String tenantId, String resourceId);
I had started to comment over there, but for all three of the API query types you'll return `PagedContent` (populated from a `Page`). In the case of query by envoyId, use the `PageContent.ofSingleton` to unify that response regardless of single value or paged values.

2020-09-29 01:53 UTC, jjbuchan requested changes

2020-09-29 01:53 UTC, jjbuchan commented on src/main/java/com/rackspace/salus/telemetry/entities/AgentHistory.java
> +  @Column(name ="connected_timestamp", nullable = false)
@shabd67 annotating the non-null fields with `@NotNull` would be good to do.

2020-09-29 13:24 UTC, itzg approved these changes
Looks good. Please wait on @jjbuchan 's re-review before merging.

2020-09-29 17:30 UTC, jjbuchan submitted a review, later dismissed

2020-09-30 13:34 UTC, itzg approved these changes

2020-10-01 04:07 UTC, jjbuchan approved these changes

2020-10-01 08:11 UTC, merged