Created new table to track jobs
racker/salus-telemetry-model pull request #161
Opened 2020-10-15 16:59 UTC by rohitsngh27

# Resolves
https://jira.rax.io/browse/SALUS-1051

# What
A new table is created to keep track of the jobs results.

# How
Created new table and repository.

2020-10-19 06:19 UTC, jjbuchan requested changes

2020-10-19 06:19 UTC, jjbuchan commented on src/main/java/com/rackspace/salus/telemetry/model/JobStatus.java
> +  SUCCESS, FAILURE
I'd expect an `IN_PROGRESS` as well.  Especially since this field is `@NotNull`.  Something should be inserted when the job starts.

2020-10-19 06:19 UTC, jjbuchan commented on src/main/java/com/rackspace/salus/telemetry/entities/Jobs.java
> +  String name;
I think this should either use the enum `JobName` or the `JobName` class should be removed and we just allow any string.

Slightly indifferent to what option is chosen.  I can see benefits to both.

2020-10-19 11:06 UTC, rohitsngh27 commented on src/main/java/com/rackspace/salus/telemetry/entities/Jobs.java
> +  String name;
I am using value of JobName enums to store in database that's why I made it as String here.

2020-10-19 14:47 UTC, itzg requested changes

2020-10-19 14:47 UTC, itzg commented on src/main/java/com/rackspace/salus/telemetry/entities/Jobs.java
> +public class Jobs implements Serializable {
nit: we use singular class names, but plural table names
```suggestion
public class Job implements Serializable {
```

2020-10-19 14:47 UTC, itzg commented on src/main/java/com/rackspace/salus/telemetry/entities/Jobs.java
> +  String name;
> I am using value of JobName enums to store in database that's why I made it as String here.

If sticking with the enum, I prefer database fields to use `@Enumerated(EnumType.STRING)` like `status` rather than a label-type string.

2020-10-19 14:47 UTC, itzg commented on src/main/java/com/rackspace/salus/telemetry/entities/Jobs.java
> +  String description;
Can you add javadoc to this one to remind us what is typical/expected to go in this field?

2020-10-19 14:47 UTC, itzg commented on src/main/java/com/rackspace/salus/telemetry/model/JobName.java
> +public enum JobName {
Seeing the enum, it seems like this should be called `JobType` and the field in `Job` be renamed to `type`. As `name` it seems like it should be more open-ended and arbitrary, which might be fine too.

2020-10-19 14:47 UTC, itzg commented on src/main/java/com/rackspace/salus/telemetry/repositories/JobsRepository.java
> +public interface JobsRepository extends CrudRepository<Jobs, String> {
```suggestion
public interface JobRepository extends CrudRepository<Jobs, String> {
```

2020-10-19 15:30 UTC, rohitsngh27 commented on src/main/java/com/rackspace/salus/telemetry/entities/Jobs.java
> +  String name;
So I should remove the values from this enum. Right?

2020-10-19 15:31 UTC, itzg commented on src/main/java/com/rackspace/salus/telemetry/model/JobName.java
> +public enum JobName {
You can keep them if you want for possible API response enrichment or logging

2020-10-19 15:51 UTC, jjbuchan submitted a review, later dismissed
An optional nit

2020-10-19 15:51 UTC, jjbuchan commented on src/main/java/com/rackspace/salus/telemetry/model/JobType.java
> +  DELETE_TENANT("Delete tenant");
```suggestion
  DELETE_TENANT("Delete Tenant");
```

I hesitated on being this picky last night, but the lowercase `t` is still bugging me a little :)

2020-10-19 16:05 UTC, itzg approved these changes

2020-10-20 15:44 UTC, jjbuchan commented on src/main/java/com/rackspace/salus/telemetry/model/JobType.java
> +  DELETE_TENANT("Delete Tenant");
Per my comment in https://github.com/racker/salus-telemetry-monitor-management/pull/221/files

We might want to rename or add a job for `DELETE_TENANT_MONITORS`

2020-10-20 15:45 UTC, rohitsngh27 commented on src/main/java/com/rackspace/salus/telemetry/model/JobType.java
> +  DELETE_TENANT("Delete Tenant");
Yes renaming it will make more sense

2020-10-20 20:43 UTC, itzg approved these changes

2020-10-21 03:01 UTC, jjbuchan approved these changes

2020-10-21 12:26 UTC, merged